### ISSUE TITLE
8.0.x todo list

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3432]
This is the big, "what needs to happen before 8.0.0 can be released". Some things depend on others, and some have been assigned to me or other people who will implement them.

Note that this is (partially) shown in https://github.com/BuildCraft/BuildCraft/projects/1

Api:
- [ ] Ensure that the Mj API is simple and useful. Feedback required, especially for the `IMjConnectorType` bit as I'm not sure how useful it will be. Also an item interface would probably make sense, as some-one will want to implement batteries or charge robots in a charging table.(EDIT: This PROBABLY means removing the "IMjConnectorType" class and related implementing classes as I don't really see how they could be helpful).
- [ ] ~~Ensure that the new schematic task API is clearly defined and usable. Its not quite finished yet though so feedback is mostly just internally done via its implementation in the Builder and Filler.~~ Revert the builder code to the code in 7.2.x as it turns out the new set of classes and API's were not useful in any way (Assigned to @AlexIIL)

Lib:
- [ ] Split off the implementation of TileAutoWorkbenchBase into a seperate class as then the adv crafting table can use that code for its own crafting.
- [ ] Implement an instant blueprint builder for looking at the blueprint items you hold, and for making built structures in the guide book. (Assigned to @AlexIIL)
- [ ] Test the usage of the guide book with images and blueprints (Waiting for the above).

Core:
- [ ] Test the marker implementation thoroughly (This needs people to test and report bugs with it, ideally finding a way to fix them)
- [x] Port the spring block as-is
- [ ] Make the engine blocks work well with the new Mj System (Assigned to @AlexIIL)

Builders:
- [ ] Implement the builder (Assigned to @AlexIIL)
- [ ] Implement the filler (Assigned to @AlexIIL)
- [ ] Implement the animation manager with a little flying robot for block breaks, and thrown out items for block building. (Assigned to @AlexIIL)
- [ ] Implement a block for editing blueprints and templates. (Assigned to @AlexIIL)
  1. Allowing all 3 axis of rotation, and 3 axis of mirroring
  2. Replace all types of a block with another type.
- [ ] Implement a block for adding single blueprints together to form a "combinded blueprint" which is just a few blueprints stuck together.

Energy:
- [ ] Implement the full complex refining setup. This might go in factory, I'm not quite sure yet. (Assigned to @AlexIIL)

Factory:
- [ ] Make the quarry start with a default sized frame of ?x4x?
- [ ] Make the quarry look around when placed to try and find valid existing frames to use as a frame (rather than always require landmarks)
- [ ] Make the quarry require and build a 3d frame (min height of 4) rather than a 2d one
- [ ] ~~Make the water gel turn into a pumpable fluid at the end of its gelling stage instead of a block.~~ (not sure, invalid now)

Transport:
- [x] Rewrite the pipe base code. (Assigned to @AlexIIL)
- [x] Rewrite the pipe pluggable code (Assigned to @AlexIIL)
- [x] Rewrite the base gate code.(Assigned to @AlexIIL)
- [ ] Implement all of the existing pluggables from 7.2.x (Assigned to @AlexIIL)
- [x] Fix the pipe bounding box (Waiting for the pipe base code)

Silicon:
- [x] Port the redstone chipset, removing the "puslating", "comp" and "emerald" variants. (Being implemented by afdw)
- [ ] Port the advanced crafting table (Waiting for the splitting up of TileAutoWorkbench base code) 
- [ ] Change the programming table to work with the new robot plans (Assigned to @AlexIIL)
- [x] Change all the table models to use minecraft's json model format rather than the wavefront format.

Robotics:
- [ ] Port existing robot code (Waiting for the pluggable code)
- [ ] Change the way robots work to be simalir to asie's plans in #3113 (Assigned to @AlexIIL)

General:
- [ ] Write usage (+lore) for all items + blocks in BC for the guide book. Most likely going to be done by @AlexIIL

**Comment by AEnterprise** [comment]
once the MJ api is done give me a ping, i wasn't involved in making it so i can take a look as 'outsider' to see if it's easy/clear to use and figure out

**Comment by SourcePowered** [comment]
For 1.10.2 ?

**Comment by AlexIIL** [comment]
@SourcePowered yes

**Comment by Tencao** [comment]
Will there be any jenkins dev builds to allow us to test for bugs and other issues before a release is made, or are you just going for a beta release.

**Comment by afdw** [comment]
Now there are ~2500 compiling errors, so now no.

**Comment by AlexIIL** [comment]
@Tencao Unfortunately we are not yet close enough to that (there is still a bit of core code missing and the old license stuff hasn't been cleaned up yet as we are still porting it). However a set of pre-releases will probably happen when we get all of that done for proper bug testing.

**Comment by Tencao** [comment]
Thats fine, I'll wait for the pre-releases before testing, just glad to see it's moving forward.

**Comment by TheMrCaveman** [comment]
Thanks for sharing!

**Comment by Shybella** [comment]
Yes, very exciting!

**Comment by ozhound** [comment]
@AlexIIL, i am a tester for the AllTheMods Modpack. We have worked with the AE team in testing and providing bug reports on a production server prior to alpha release of the mod to the general public. We can offer the same for buildcraft if you are open to some pre-alpha testing externally (when you think the build is close to alpha). Rest assured the AE builds were not distributed as our testing server is a closed whitelisted server which required the AE jar to be installed manually as it wasn't included in the modpack via the curse client. The Testing server only has about 10 players but we are all seasoned MC'ers.

Regards

Ozhound

**Comment by asiekierka** [comment]
We have already had a private testing team who has handled a large amount
of the testing work for BuildCraft 6.x. Either way, we don't mind - if you
compile your own builds and ensure that the bug reports are of sufficiently
high politeness and detail, I don't think anyone will complain.

2016-11-04 13:37 GMT+01:00 ozhound <notifications@github.com>:

**Comment by AEnterprise** [comment]
if you guys want to build it to test it that's fine but please make sure to not compile it with a regular BC version number, add something to it to make it clear that it isn't a regular build and include that in the bug report as well, also helpfull in bug reports for custom builds would be what commit was that was used to compile from, then it is easy to determine if it has already been fixed in dev or if it's a regression

**Comment by LuigiHutch** [comment]
I don't think it even compiles ATM ;D

**Comment by afdw** [comment]
You can use Eclipse compiler, which can ignore errors.

**Comment by TheMrCaveman** [comment]
So how is the progres going?

**Comment by meelock** [comment]
How do you setup eclipse with this, I ran setupdecompworkspace and eclipse, yet no eclipse folder is appearing!

**Comment by TheMrCaveman** [comment]
?

**Comment by Tencao** [comment]
Look under projects for a rough idea, otherwise look at the checkmarks at the top. Additionally you can also look at the commits being done

**Comment by Enter03** [comment]
I know that my question isn't related with this page but:

Is there any planned release date for Buildcraft for MC 1.10 / 1.10.2 (8.0.X) I can't wait to play on survival mode.

Sorry for bad English and please answer. :)

**Comment by Tencao** [comment]
It's being developed for 1.10.2, so yes.

**Comment by AlexIIL** [comment]
At the moment the 8.0.x branch is 1.10.2, but it will be migrated to 1.11 soonish.

**Comment by Joshwoo70** [comment]
i mght be able to help with the lore part of BC. what do we need?

**Comment by Sellec** [comment]
Is there any way to download any prerelease build of buildcraft to test it on 1.10.2?

**Comment by Kuktar** [comment]
I wish I could get ahold of BC becuase I'm lost on 1.10.2 so far I am resorting on enderio becuase i never used mechanism before.

**Comment by Kuktar** [comment]
Also I want buildcraft quarry. What's the point of minecraft if all your ore comes from the void.... I miss big ass empty chunks lol

**Comment by AlexIIL** [comment]
@Joshwoo70 Its mostly just light lore about what the different blocks + items do and why some of them are needed - however I don't want to open up the guide for editing just yet because I want to finalise the special markdown formatting elements used, the folder structure for organising it, and have pretty much finalised every part of BC 8.0.0.

@Sellec no. Partly because development has moved to 1.11.2, but mostly because most of the content is being actively worked on or hasn't been implemented.

@Kuktar Unfortunately its not ready yet, and even if you could get a version right now it's buggy and not survival-ready (and to fix bugs I might have to break the way saving+loading worked.

**Comment by AlexIIL** [comment]
This is being closed as https://github.com/BuildCraft/BuildCraft/projects/1 tracks this much better than this issue description.

**Comment by Enter03** [comment]
@Kuktar You can't download release (jar file) but you can download project and compile it with few Gradle commands. I compiled BuildCraft and it works with 1.10! (But it's not finished yet — many bugs, lags.)

**Comment by Kuktar** [comment]
Really I have never used gradle before. I would love to beta test :)

**Comment by Sellec** [comment]
@Enter03 can you send a compiled version of buildcraft? i had never work with java and dont now how to compile it and what tools is need for it.

**Comment by asiekierka** [comment]
If you haven't worked with Java before, it's probably too early for you to use BuildCraft 8.0.x alphas. Wait for a release.

**Comment by Joshwoo70** [comment]
worked with java.. anyway to get it compiling for IntelIJ IDEA?

**Comment by AEnterprise** [comment]
you should be able to just remove the non compiling legacy code, iirc it's only just there atm for reference after the porting

**Comment by Enter03** [comment]
@Kuktar I never worked with Java too. I can send you compiled jar but I need permissions from author. Maybe this can help: http://www.minecraftforge.net/forum/index.php?topic=15232.0 or this: https://www.google.pl/search?q=how+to+compile+minecraft+mods+from+github&ie=UTF-8&oe=UTF-8&hl=pl-pl&client=safari

**Comment by Enter03** [comment]
And before compiling make sure that ALL dependencies are in project folder.

**Comment by Tencao** [comment]
I have a compiled version already, however I can tell you from experience this is far too broken to be used at all right now. Some items will flat out crash your game, while others can cause massive corruption. Just be patient and wait for things to get finished.

**Comment by Enter03** [comment]
@Tencao I hate waiting... :(

@AlexIIL I can help update Polish translation (of course for free but not more that 1500 messages)

**Comment by AlexIIL** [comment]
@Enter03 I haven't finalised the lang keys yet so its too early to translate the new keys + texts.

**Comment by Enter03** [comment]
@AlexIIL Ok, so when you finish English lang files, then i can translate them to Polish.

If you want my help in translations, then write to me.

**Comment by Fungie2134** [comment]
Is there a jenkins for 1.10.2 ?

**Comment by AEnterprise** [comment]
@Fungie2134 BC skipped 1.10.2 so there can't be a jenkins for it
